resources:
- name: repo
  type: git
  source:
    uri: git@github.com:benhardy06/docker-concourse.git
    branch: master
    private_key: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABA0V/Gbbg
        6IMoI1nuQBlP+zAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIFtlOHasLABVXPVj
        Udyp8Vv25hZ+HehbhZXYG38y3NDkAAAAoCuMfTCqeUYbeKj0EBlfL6d5mW4OV4Kx1Tm0d/
        AAu+MjVZNdTDRrvkYm4DIusBzeQ3gZxUZzEdFsEVxoSqORIujTKQgsZVi5fbQ+ro29BevC
        sESfeEB4gQnWAhHAuh9/913n+vqtH1s41cfgSp9UTl4dnsZOJqxd4/0ifbE6dEHr4JpSU1
        POoqFmXWhaQ8Z2zGzaYIyP2PYql9Rqse8elt4=
        -----END OPENSSH PRIVATE KEY-----
    private_key_passphrase: "concourse"
 
jobs:
  - name: build-and-deploy
    plan:
      # Step 1: Get the repository
      - get: repo
        trigger: true
      
      # Step 2: Build the application
      - task: build
        file: concourse/tasks/build.yaml
        input_mapping:
          repo: repo
        output_mapping:
          built-artifacts: built-artifacts