platform: linux

image_resource:
  type: registry-image
  source:
    repository: python
    tag: "3.9"

inputs:
  - name: repo

run:
  path: sh
  args:
    - -exc
    - |

      # Check if port 8000 is available
      if ! nc -z localhost 8000; then
          echo "Port 8000 is available. Starting the HTTP server..."
          cd repo
          # Start the HTTP server
          python -m http.server 8000 &
      else
          echo "Port 8000 is already in use."
          exit 1
      fi