platform: linux

image_resource:
  type: registry-image
  source:
    repository: python
    tag: "3.9"

inputs:
  - name: repo

outputs:
  - name: repo

run:
  path: sh
  args:
    - -exc
    - |

      cd repo
      # Start the HTTP server
      python -m http.server 8000