
platform: linux

image_resource:
  type: registry-image
  source:
    repository: alpine-chrome 

inputs:
  - name: repo

outputs:
  - name: repo

run:
  path: sh
  args:
    - -exc
    - |
      # Navigate to the source code directory

      cd repo
      
      npx playwright install  

      npx playwright install-deps

      # Build the application (replace this command with your actual build command)
      npx codeceptjs run
