
platform: linux

image_resource:
  type: registry-image
  source:
    repository: node
    tag: "18.17.0" 

inputs:
  - name: repo

outputs:
  - name: repo

run:
  path: sh
  args:
    - -exc
    - |
      # Navigate to the source code directory
      cd repo
      
      npx playwright install  

      # Build the application (replace this command with your actual build command)
      npx codeceptjs run
